idf_component_register(
    SRCS
        "src/camera_service.cpp"
        "src/mjpeg_service.cpp"
        "src/led_strip_service.cpp"
    INCLUDE_DIRS
        "include"
    REQUIRES
        embed
        esp_http_server
        esp32-camera
        led_strip
        freertos
        log
        heap
)
