## MQTT
mqtt.listeners.tcp.default = 1883
mqtt.allow_anonymous = false
mqtt.vhost = /
mqtt.exchange = amq.topic
mqtt.prefetch = 10

## MQTT over WebSockets (browser / dashboard tooling)
web_mqtt.tcp.port = 15675

## Management UI
management.tcp.port = 15672

## Logging
log.console = true
log.console.level = info
