idf_component_register(
    SRCS
        "src/wifi_service.cpp"
        "src/mqtt_service.cpp"
        "src/metrics_service.cpp"
        "src/nvs_store.cpp"
        "src/device_settings.cpp"
        "src/config_portal_service.cpp"
        "src/firmware_slot.cpp"
    INCLUDE_DIRS
        "include"
    REQUIRES
        embed
        esp_wifi
        esp_netif
        esp_event
        nvs_flash
        esp_partition
        mqtt
        esp_timer
        esp_system
        log
        freertos
        esp_http_server
        esp_driver_gpio
        app_update
    PRIV_REQUIRES
        spiffs
        mbedtls
)
